services:
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"

  # data-receiver:
  #   image: data-receiver
  #   build:
  #     context: ../src
  #     dockerfile: ../deploy/data_receiver.dockerfile
  #   environment:
  #     - MQTT_BROKER=mqtt
  #     - MQTT_PORT=1883
  #   depends_on:
  #     - mqtt



